image: python:3.7

# Change pip's package cache directory to be inside the project directory to allow caching via Gitlab CI
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V               # Print out python version for debugging

test:
  script:
  - pip install --cache-dir="$PIP_CACHE_DIR" mypy
  - python -m unittest
  - mypy aas
