image: python:3.6

# Change pip's package cache directory to be inside the project directory to allow caching via Gitlab CI
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    COUCHDB_USER: "admin"
    COUCHDB_PASSWORD: "yo0Quai3"

services:
  - couchdb:2.3

cache:
  paths:
    - .cache/pip

before_script:
  - python -V               # Print out python version for debugging

test:
  stage: test
  script:
  # Install python testing dependencies
  - pip install --cache-dir="$PIP_CACHE_DIR" mypy pycodestyle unittest-xml-reporting coverage
  - pip install --cache-dir="$PIP_CACHE_DIR" -r requirements.txt
  # Setup test config and CouchDB database server
  - echo -e "[couchdb]\nurl = http://couchdb:5984" > test/test_config.ini
  - python test/_helper/setup_testdb.py -u "$COUCHDB_USER" -p "$COUCHDB_PASSWORD"
  # Add source directory to PYTHONPATH to allow testing our CLI scripts, which import our modules
  - export PYTHONPATH=".:$PYTHONPATH"
  # Run tests
  - coverage run --source aas --branch -m xmlrunner -o testreports
  # Report test coverage; check typing and codestyle
  - coverage report -m
  - mypy aas test bin
  - python -m pycodestyle --count --max-line-length 120 aas test

  artifacts:
    reports:
      junit: testreports/*.xml

  only: [branches, tags, merge_requests]
