image: python:3.6

# Change pip's package cache directory to be inside the project directory to allow caching via Gitlab CI
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V               # Print out python version for debugging

test:
  script:
  - pip install --cache-dir="$PIP_CACHE_DIR" mypy pycodestyle unittest-xml-reporting coverage
  - pip install --cache-dir="$PIP_CACHE_DIR" -r requirements.txt
  - coverage run --source aas --branch -m xmlrunner -o testreports
  - coverage report -m
  - mypy aas test
  - python -m pycodestyle --count --max-line-length 120 aas test

  artifacts:
    reports:
      junit: testreports/*.xml
